# LANGUAGE message translation file for plpython
# Copyright (C) 2011 PostgreSQL Global Development Group
# This file is distributed under the same license as the PostgreSQL package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2011.
# Begina Felicysym <begina.felicysym@wp.eu>, 2011.
msgid ""
msgstr ""
"Project-Id-Version: PostgreSQL 9.1\n"
"Report-Msgid-Bugs-To: pgsql-bugs@postgresql.org\n"
"POT-Creation-Date: 2011-08-27 22:39+0000\n"
"PO-Revision-Date: 2011-09-01 22:37+0200\n"
"Last-Translator: Begina Felicysym <begina.felicysym@wp.eu>\n"
"Language-Team: Polish TotroiseSvn translation team\n"
"Language: pl\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 "
"|| n%100>=20) ? 1 : 2);\n"
"X-Generator: Virtaal 0.7.1-beta1\n"

#: plpython.c:515
#, c-format
msgid "PL/Python function \"%s\""
msgstr "funkcja PL/Python \"%s\""

#: plpython.c:522
#, c-format
msgid "PL/Python anonymous code block"
msgstr "anonimowy blok kodu PL/Python"

#: plpython.c:529
#, c-format
msgid "while modifying trigger row"
msgstr "podczas modyfikowania wiersza wyzwalacza"

#: plpython.c:536
#, c-format
msgid "while creating return value"
msgstr "podczas tworzenia wartości zwracanej"

#: plpython.c:747 plpython.c:773
#, c-format
msgid "unexpected return value from trigger procedure"
msgstr "nieoczekiwana wartość zwracana przez procedury wyzwalacza"

#: plpython.c:748
#, c-format
msgid "Expected None or a string."
msgstr "Oczekiwano None lub ciąg znaków."

#: plpython.c:763
#, c-format
msgid ""
"PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr ""
"funkcja wyzwalacza PL/Python zwróciła \"MODIFY\" w wyzwalaczu DELETE -- "
"zignorowano"

#: plpython.c:774
#, c-format
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "Oczekiwano None, \"OK\", \"SKIP\", lub \"MODIFY\"."

#: plpython.c:826
#, c-format
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "usunięto TD[\"new\"], nie można usunąć wiersza"

#: plpython.c:829
#, c-format
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] nie jest słownikiem"

#: plpython.c:853
#, c-format
msgid "TD[\"new\"] dictionary key at ordinal position %d is not a string"
msgstr ""
"klucz słownika TD[\"new\"] na pozycji porządkowej %d nie jest ciągiem znaków"

#: plpython.c:859
#, c-format
msgid ""
"key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering "
"row"
msgstr ""
"klucz \"%s\" znaleziony w TD[\"new\"] nie istnieje jako kolumna w wierszu "
"obsługiwanym przez wyzwalacz"

#: plpython.c:955
#, c-format
msgid "could not create new dictionary while building trigger arguments"
msgstr ""
"nie można utworzyć nowego słownika w czasie tworzenia argumentów wyzwalacza"

#: plpython.c:1162
#, c-format
msgid "unsupported set function return mode"
msgstr "nieobsługiwany tryb zwracania przez funkcję grupy"

#: plpython.c:1163
#, c-format
msgid ""
"PL/Python set-returning functions only support returning only value per call."
msgstr ""
"funkcja zwracająca grupę PL/obsługuje tylko zwracanie jednej wartości w "
"wywołaniu."

#: plpython.c:1175
#, c-format
msgid "returned object cannot be iterated"
msgstr "zwrócony obiekt nie może być przeiterowany"

#: plpython.c:1176
#, c-format
msgid "PL/Python set-returning functions must return an iterable object."
msgstr "funkcje PL/Python zwracające grupę muszą zwracać iterowalny obiekt."

#: plpython.c:1201
#, c-format
msgid "error fetching next item from iterator"
msgstr "błąd pobierania następnego elementu z iteratora"

#: plpython.c:1236
#, c-format
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "funkcja PL/Python zwracająca typ \"void\" nie zwróciła wartości None"

#: plpython.c:1327
#, c-format
msgid "forcibly aborting a subtransaction that has not been exited"
msgstr "wymuszone przerywanie podtransaction, która nie została zakończona"

#: plpython.c:1443
#, c-format
msgid "PyList_SetItem() failed, while setting up arguments"
msgstr "nie powiodło się PyList_SetItem() podczas ustawiania argumentów"

#: plpython.c:1447
#, c-format
msgid "PyDict_SetItemString() failed, while setting up arguments"
msgstr "nie powiodło się PyDict_SetItemString() podczas ustawiania argumentów"

#: plpython.c:1459
#, c-format
msgid ""
"function returning record called in context that cannot accept type record"
msgstr ""
"funkcja zwracająca rekord w wywołaniu, które nie akceptuje typów złożonych"

#: plpython.c:1693
#, c-format
msgid "trigger functions can only be called as triggers"
msgstr "procedury wyzwalaczy mogą być wywoływane jedynie przez wyzwalacze"

#: plpython.c:1698 plpython.c:2171
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "funkcje PL/Python nie mogą zwracać wartości typu %s"

#: plpython.c:1780
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "funkcje PL/Python nie obsługują typu %s"

#: plpython.c:1876
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "nie powiodła się kompilacja funkcji PL/Python \"%s\""

#: plpython.c:1879
#, c-format
msgid "could not compile anonymous PL/Python code block"
msgstr "nie udało się skompilować anonimowego bloku kodu PL/Python"

#: plpython.c:2173
#, c-format
msgid "PL/Python does not support conversion to arrays of row types."
msgstr "PL/Python nie obsługuje konwersji typów wierszowych na tablice."

#: plpython.c:2382
#, c-format
msgid "cannot convert multidimensional array to Python list"
msgstr "nie można skonwertować tablicy wielowymiarowej na listę Python"

#: plpython.c:2383
#, c-format
msgid "PL/Python only supports one-dimensional arrays."
msgstr "PL/Python obsługuje tylko jednowymiarowe tablice."

#: plpython.c:2422
#, c-format
msgid "could not create new dictionary"
msgstr "nie można utworzyć nowego słownika"

#: plpython.c:2517
#, c-format
msgid "could not create bytes representation of Python object"
msgstr "nie można utworzyć reprezentacji bajtowej obiektu Python"

#: plpython.c:2615
#, c-format
msgid "could not create string representation of Python object"
msgstr "nie można utworzyć reprezentacji znakowej obiektu Python"

#: plpython.c:2626
#, c-format
msgid ""
"could not convert Python object into cstring: Python string representation "
"appears to contain null bytes"
msgstr ""
"nie można zmienić obiektu Python na cstring: reprezentacja ciągu znaków "
"Python wydaje się zawierać puste bajty"

#: plpython.c:2660
#, c-format
msgid ""
"return value of function with array return type is not a Python sequence"
msgstr ""
"wartość zwrócona przez funkcję zwracającą tablicę nie jest sekwencją Python"

#: plpython.c:2740
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "nie odnaleziono klucza \"%s\" w mapowaniu"

#: plpython.c:2741
#, c-format
msgid ""
"To return null in a column, add the value None to the mapping with the key "
"named after the column."
msgstr ""
"Aby zwrócić null w kolumnie, dodaj wartość None do mapowania z kluczem "
"nazwanym wedle kolumny."

#: plpython.c:2789
#, c-format
msgid "length of returned sequence did not match number of columns in row"
msgstr "długość zwróconej sekwencji nie jest równa liczbie kolumn w wierszu"

#: plpython.c:2897
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "atrybut \"%s\" nie istnieje w obiekcie Python"

#: plpython.c:2898
#, c-format
msgid ""
"To return null in a column, let the returned object have an attribute named "
"after column with value None."
msgstr ""
"Aby zwrócić null w kolumnie, niech zwrócony obiekt posiada atrybut nazwany "
"wedle kolumny z wartością None."

#: plpython.c:3217
#, c-format
msgid "plan.status takes no arguments"
msgstr "plan.status nie przyjmuje żadnych argumentów"

#: plpython.c:3341
#, c-format
msgid "second argument of plpy.prepare must be a sequence"
msgstr "drugi argument plpy.prepare musi być sekwencją"

#: plpython.c:3391
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr ""
"plpy.prepare: nazwa typu na pozycji porządkowej %d nie jest ciągiem znaków"

#: plpython.c:3423
#, c-format
msgid "plpy.prepare does not support composite types"
msgstr "plpy.prepare nie obsługuje typów złożonych"

#: plpython.c:3513
#, c-format
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute oczekuje kwerendy lub planu"

#: plpython.c:3532
#, c-format
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute przyjmuje sekwencję jako drugi argument"

#: plpython.c:3548
#, c-format
msgid "could not execute plan"
msgstr "nie można wykonać planu"

#: plpython.c:3551
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "Oczekiwano sekwencji z %d argumentem, mamy %d: %s"
msgstr[1] "Oczekiwano sekwencji z %d argumentami, mamy %d: %s"
msgstr[2] "Oczekiwano sekwencji z %d argumentami, mamy %d: %s"

#: plpython.c:3693
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "nie powiódł się SPI_execute_plan: %s"

#: plpython.c:3771
#, c-format
msgid "SPI_execute failed: %s"
msgstr "nie powiódł się SPI_execute: %s"

#: plpython.c:3826
#, c-format
msgid "unrecognized error in PLy_spi_execute_fetch_result"
msgstr "nierozpoznany błąd w PLy_spi_execute_fetch_result"

#: plpython.c:3888
#, c-format
msgid "this subtransaction has already been entered"
msgstr "ta podtransakcja już została wprowadzona"

#: plpython.c:3894 plpython.c:3946
#, c-format
msgid "this subtransaction has already been exited"
msgstr "ta podtransakcja już została zakończona"

#: plpython.c:3940
#, c-format
msgid "this subtransaction has not been entered"
msgstr "ta podtransakcja nie została wprowadzona"

#: plpython.c:3952
#, c-format
msgid "there is no subtransaction to exit from"
msgstr "brak podtransakcji by z niej wyjść"

#: plpython.c:4034
#, c-format
msgid "could not add the spiexceptions module"
msgstr "nie udało się dodać modułu spiexceptions"

#: plpython.c:4117
#, c-format
msgid "Python major version mismatch in session"
msgstr "niezgodna wersja główna Python w sesji"

#: plpython.c:4118
#, c-format
msgid ""
"This session has previously used Python major version %d, and it is now "
"attempting to use Python major version %d."
msgstr ""
"Ta sesja używała poprzednio Python w głównej wersji %d, teraz próbuje użyć "
"Python w głównej wersji %d."

#: plpython.c:4120
#, c-format
msgid "Start a new session to use a different Python major version."
msgstr "Uruchom nową sesję aby użyć innej głównej wersji Python."

#: plpython.c:4135
#, c-format
msgid "untrapped error in initialization"
msgstr "niewyłapany błąd w inicjacji"

#: plpython.c:4163
#, c-format
msgid "could not import \"__main__\" module"
msgstr "nie udało się zaimportować modułu \"__main__\""

#: plpython.c:4170
#, c-format
msgid "could not initialize globals"
msgstr "nie można zainicjować zmiennych globalnych"

#: plpython.c:4285
msgid "could not parse error message in plpy.elog"
msgstr "nie można przetworzyć komunikatu błędu w plpy.elog"

#: plpython.c:4309 plpython.c:4541 plpython.c:4542
#, c-format
msgid "%s"
msgstr "%s"

#: plpython.c:4896
#, c-format
msgid "could not convert Python Unicode object to PostgreSQL server encoding"
msgstr ""
"nie można zmienić obiektu unikodowego Python na kodowanie serwera PostgreSQL"
